### ISSUE TITLE
Add Feature - Ignore URL patterns

### ISSUE THREAD

**Issue by hyunjiLeeTech** [tuidamon/Webpage-status-checking-tool#9]
Hi, I would like to add a feature to ignore URL pattern(s) using text file. For example, if you write 'https://google.com" in the text file, your tool will ignore the urls include "https://google.com". 

Please let me know if I can work on this feature.

**Comment by hyunjiLeeTech** [comment]
I've pushed pull request (https://github.com/tuidamon/Webpage-status-checking-tool/pull/10) for two commits (c73ee3d, 22d658c) for this issue. Please have a look at it and let me know if there's anything I need to fix for this issue. Thanks.

**Comment by tuidamon** [comment]
Sure, do whatever you like. And thanks for your help! : )

**Comment by hyunjiLeeTech** [comment]
Closed by PR: https://github.com/tuidamon/Webpage-status-checking-tool/pull/10. The commits are the following: c73ee3d, 22d658c.
